name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"
  SOLUTION_PATH: "./GymManagement.sln"

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: dotnet test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: gymmanagement-artifact
          path: artifacts/
