name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0
  SOLUTION_FILE: "./GymManagement.sln"

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet test
        run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.SOLUTION_FILE }} --configuration Release -o artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: gymmanagement-artifact
          path: artifacts/
